# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog_from_git_commits(commits_count: 1)

    increment_build_number(
      build_number: ENV['TRAVIS_BUILD_NUMBER']
    )
    
    sync_code_signing(type: 'appstore', readonly: true)
    build_app(scheme: "Stock Tracking")
    upload_to_testflight(distribute_external: true, groups: "Hackathon")
  end

  lane :icon do
    appicon(
      appicon_image_file: 'fastlane/icon.png',
      appicon_path: 'Stock Tracking/Assets.xcassets',
      appicon_devices: %i[ipad iphone ios_marketing]
    )
  end
end
